name: CI

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull 777shuang/pandoc-python

      - name: Convert documents
        run: |
          DIRS=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./##`
          docker run -v "`pwd`:/workdir" 777shuang/pandoc-python ${DIRS}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "LaTeX"
          path: "*/*.tex"