name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    container: 
      image: 777shuang/md2pdf

    steps:
      - name: Checkout
        uses: actions/checkout@v3
