name: CI

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:  
  pandoc:
    runs-on: ubuntu-latest
    container:
      image: 777shuang/pandoc-python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert documents
        run: |
          DIRS=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./##`
          python3 ${PYTHON_SCRIPT} ${DIRS}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "LaTeX"
          path: "*/*.tex"

  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.matrix.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: matrix
        run: |
          list=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./## | jq -R -s -c 'split("\n")[:-1]'`
          echo $list
          echo "dirs=${list}" >> $GITHUB_OUTPUT

  latex:
    needs: get_matrix
    runs-on: ubuntu-latest
    container:
      image: 777shuang/latex
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.get_matrix.outputs.dirs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LaTeX

      - name: Compile documents
        run: |
          cp /root/.latexmkrc .latexmkrc
          latexmk -cd ${{ matrix.value }}/${{ matrix.value }}.tex
          mv ${{ matrix.value }}/${{ matrix.value }}.pdf ${{ matrix.value }}.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "PDF"
          path: ${{ matrix.value }}.pdf