name: CI

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:
  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.matrix.outputs.dirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - id: matrix
        run: |
          array=(${{ steps.changed-files.outputs.all_changed_files }})
          for i in "${!array[@]}"; do
            while [[ "$array[$i]" =~ "/" ]]; do
              array[i]=`dirname $array[$i]`
            done
          done
          dirs=()
          i=0
          while read -r x; do
            dirs[i++]="$x"
          done < <(printf '%s\n' "${array[@]}" | sort -u)
          list=`echo ${dirs[@]} | jq -R -s -c 'split(" ")[:-1]'`
          echo $list
          echo "dirs=${list}" >> $GITHUB_OUTPUT

  build:
    needs: get_matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        value: ${{ fromJson(needs.get_matrix.outputs.dirs) }}
    container: 
      image: 777shuang/pandoc:docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: python3 build.py ${{ matrix.value }}
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.value }}
          path: |
            ${{ matrix.value }}/${{ matrix.value }}.pdf
