name: CI

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:
  pandoc:
    runs-on: ubuntu-latest
    container:
      image: 777shuang/pandoc-python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert documents
        run: |
          DIRS=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./##`
          python3 ${PYTHON_SCRIPT} ${DIRS}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "LaTeX"
          path: "*/*.tex"

  latex:
    runs-on: ubuntu-latest
    container:
      image: 777shuang/latex
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LaTeX

      - name: Compile documents
        run: |
          cp /root/.latexmkrc .latexmkrc
          DIRS=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./##`
          for DIR in ${DIRS}; do
            latexmk -cd ${DIR}/${DIR}.tex
            mv ${DIR}/${DIR}.pdf ${DIR}.pdf
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "PDF"
          path: "*.pdf"