name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    container: 
      image: 777shuang/pandoc:docker

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert
        run: |
          for dir in `find . -type d -name '.*' -prune -o -type d -print`; do
            cat $dir/*.md > $dir/`basename $dir`.md
            sed -i s/、/，/g $dir/`basename $dir`.md
            pandoc -sN -f markdown -t latex --template template.tex $dir/`basename $dir`.md -o $dir/`basename $dir`.tex
            uplatex $dir/`basename $dir`.tex
            uplatex $dir/`basename $dir`.tex
            dvipdfmx $dir/`basename $dir`.dvi
          done

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            **.pdf
