name: CI

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:
  pandoc:
    runs-on: ubuntu-latest
    container:
      image: 777shuang/pandoc-python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert documents
        run: |
          DIRS=`find . -mindepth 1 -maxdepth 1 -type d -name '.git*' -prune -o -type d -print | sed -e s#./##`
          python3 ${PYTHON_SCRIPT} ${DIRS}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "LaTeX"
          path: "*/*.tex"