name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt update

      - run: sudo apt upgrade -y

      - name: Install ghcup
        run: curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

      - run: cabal update

      - run: cabal install pandoc-cli

      - run: pandoc -v
