name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    container: 
      image: 777shuang/pandoc

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Markdown Files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.md

      - name: Convert
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pandoc -sN -f markdown -t latex --template template.tex $file -o $file.tex
            uplatex $file.tex
            uplatex $file.tex
            dvipdfmx $file.dvi
          done

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            **.pdf
